language: node_js
install:
  - "npm install"
  - "npm run bootstrap"
  - "npm run tsc"
  - "npm run tslint"
  - "npm run test"

node_js:
  - "12"
  - "10"


notifications:
  email:
    recipients:
      - team@jovo.tech
    on_success: never
    on_failure: always

